version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: stockbud-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: stockbud-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  postgres:
    image: postgres:15
    container_name: stockbud-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stockbud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: stockbud-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stockbud.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: stockbud-grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stockbud-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./backend/data:/app/data

  order-processor:
    build:
      context: ./backend/order-processor
      dockerfile: Dockerfile
    container_name: stockbud-order-processor
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - ./backend/order-processor/.env
    depends_on:
      - rabbitmq

  image-service:
    build:
      context: ./backend/image-service
      dockerfile: Dockerfile
    container_name: stockbud-image-service
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - ./backend/image-service/.env
    depends_on:
      - rabbitmq

  shopify-app:
    build:
      context: ./stockbud
      dockerfile: Dockerfile
    container_name: stockbud-shopify-app
    restart: always
    ports:
      - "3004:3000"
    env_file:
      - ./stockbud/.env
    environment:
      - STOCKBUD_BACKEND_URL=http://backend:3000
      - SHOPIFY_APP_URL=https://your-app-domain.com # Update this to your public domain
      - NODE_ENV=production
    depends_on:
      - backend
    volumes:
      - shopify_data:/data

volumes:
  rabbitmq_data:
  postgres_data:
  grafana_data:
  shopify_data:
