# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1131bed562962ede818c27c2f4c0081"
name = "Stockbud"
application_url = "https://shopify.stockbud.xyz"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [webhooks.privacy_compliance]
  customer_deletion_url = "/webhooks/customers/redact"
  customer_data_request_url = "/webhooks/customers/data_request"
  shop_deletion_url = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify.stockbud.xyz/auth/callback",
  "https://shopify.stockbud.xyz/auth/shopify/callback",
  "https://shopify.stockbud.xyz/api/auth"
]
